plugins {
    id "com.android.application"
}

android {
    namespace "dev.afdo.lineagepillcts"
    compileSdk 36

    defaultConfig {
        applicationId "dev.afdo.lineagepillcts"
        minSdk 35
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
    }
}

dependencies {
    compileOnly project(":xposed-stub")
}
